spring:
  application:
    name: sharing_blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 1234
  data:
    redis:
      port: 6379
      host: localhost
  mvc:
    servlet:
      load-on-startup: 100
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888
